### ISSUE TITLE
Login loop after interaction with first pokestop

### ISSUE THREAD

**Issue by nubs4sale** [PocketMobsters/MobBotTemp#14]
After the first pokestop is spun, the following error is thrown leading to another login.  This cycles over and over again.

System.NullReferenceException: Object reference not set to an instance of an object.
   at PoGo.PokeMobBot.Logic.HumanNavigation.<Move>d__2.MoveNext() in C:\Users\Junior\Source\Repos\MobBotTemp\PoGo.PokeMobBot.Logic\Navigation2.cs:line 52
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PoGo.PokeMobBot.Logic.Tasks.FarmPokestopsTask.<NoTeleport>d__3.MoveNext() in C:\Users\Junior\Source\Repos\MobBotTemp\PoGo.PokeMobBot.Logic\Tasks\FarmPokestopsTask.cs:line 355
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PoGo.PokeMobBot.Logic.Tasks.FarmPokestopsTask.<Execute>d__1.MoveNext() in C:\Users\Junior\Source\Repos\MobBotTemp\PoGo.PokeMobBot.Logic\Tasks\FarmPokestopsTask.cs:line 33
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PoGo.PokeMobBot.Logic.State.FarmState.<Execute>d__0.MoveNext() in C:\Users\Junior\Source\Repos\MobBotTemp\PoGo.PokeMobBot.Logic\State\FarmState.cs:line 53
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PoGo.PokeMobBot.Logic.State.StateMachine.<Start>d__3.MoveNext() in C:\Users\Junior\Source\Repos\MobBotTemp\PoGo.PokeMobBot.Logic\State\StateMachine.cs:line 37

**Comment by FabryB** [comment]
This is due to query to routing server failure. It is addressed in my PR #15

**Comment by xfaustx** [comment]
same here

**Comment by PocketMobsters** [comment]
It is fixed
