### ISSUE TITLE
Routing error + Exception

### ISSUE THREAD

**Issue by cvbkf** [PocketMobsters/MobBotTemp#22]
Sometimes, i get these errors when arriving at a pokestop

[12:30:32] (INFO) Arriving to Pokestop: War Memorial in (19m)
Routing error: The connection with the remote server couldn't be established
[12:30:53] (ERROR) System.NullReferenceException: Object reference not set to an instance of an object.
   at PoGo.PokeMobBot.Logic.HumanNavigation.<Move>d__2.MoveNext() in C:\Users\Junior\Source\Repos\MobBotTemp\PoGo.PokeMobBot.Logic\Navigation2.cs:line 52.
--- end of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PoGo.PokeMobBot.Logic.Tasks.FarmPokestopsTask.<NoTeleport>d__3.MoveNext() in C:\Users\Junior\Source\Repos\MobBotTemp\PoGo.PokeMobBot.Logic\Tasks\FarmPokestopsTask.cs:line 355.
--- end of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PoGo.PokeMobBot.Logic.Tasks.FarmPokestopsTask.<Execute>d__1.MoveNext() in C:\Users\Junior\Source\Repos\MobBotTemp\PoGo.PokeMobBot.Logic\Tasks\FarmPokestopsTask.cs:line 33.
--- end of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PoGo.PokeMobBot.Logic.State.FarmState.<Execute>d__0.MoveNext() in C:\Users\Junior\Source\Repos\MobBotTemp\PoGo.PokeMobBot.Logic\State\FarmState.cs:line 53.
--- end of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PoGo.PokeMobBot.Logic.State.StateMachine.<Start>d__3.MoveNext() in C:\Users\Junior\Source\Repos\MobBotTemp\PoGo.PokeMobBot.Logic\State\StateMachine.cs:line 37.
[12:30:53] (INFO) Logging in using account Ptc

**Comment by cvbkf** [comment]
fixed by 2.0.1
