### ISSUE TITLE
string of errors

### ISSUE THREAD

**Issue by cokuspocus** [PocketMobsters/MobBotTemp#31]
[10:11:57] System.ArgumentNullException: Value cannot be null.
Parameter name: ptr
   at System.Runtime.InteropServices.Marshal.GetDelegateForFunctionPointer(IntPtr ptr, Type t)
   at PokemonGo.RocketAPI.Helpers.RequestBuilder.FunctionLoader.LoadFunction[T](String dllPath, String functionName) in C:\Users\Junior\Source\Repos\MobBotTemp\Pokemon-Go-Rocket-API\PokemonGo.RocketAPI\Helpers\RequestBuilder.cs:line 191
   at PokemonGo.RocketAPI.Helpers.RequestBuilder..ctor(String authToken, AuthType authType, Double latitude, Double longitude, Double altitude, ISettings settings, AuthTicket authTicket) in C:\Users\Junior\Source\Repos\MobBotTemp\Pokemon-Go-Rocket-API\PokemonGo.RocketAPI\Helpers\RequestBuilder.cs:line 46
   at PokemonGo.RocketAPI.Rpc.BaseRpc.get_RequestBuilder() in C:\Users\Junior\Source\Repos\MobBotTemp\Pokemon-Go-Rocket-API\PokemonGo.RocketAPI\Rpc\BaseRpc.cs:line 18
   at PokemonGo.RocketAPI.Rpc.Login.<SetServer>d__4.MoveNext() in C:\Users\Junior\Source\Repos\MobBotTemp\Pokemon-Go-Rocket-API\PokemonGo.RocketAPI\Rpc\Login.cs:line 73
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Rpc.Login.<DoLogin>d__3.MoveNext() in C:\Users\Junior\Source\Repos\MobBotTemp\Pokemon-Go-Rocket-API\PokemonGo.RocketAPI\Rpc\Login.cs:line 59
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PoGo.PokeMobBot.Logic.State.LoginState.<Execute>d__0.MoveNext() in C:\Users\Junior\Source\Repos\MobBotTemp\PoGo.PokeMobBot.Logic\State\LoginState.cs:line 31
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PoGo.PokeMobBot.Logic.State.StateMachine.<Start>d__3.MoveNext() in C:\Users\Junior\Source\Repos\MobBotTemp\PoGo.PokeMobBot.Logic\State\StateMachine.cs:line 37
[10:11:57] Logging in using account Ptc

no idea what this stuff is asking lmao but happens whenever i try to run

**Comment by xfaustx** [comment]
If ya cant login into your acc on phone getting error Failed to get data than ya got banned.

**Comment by cokuspocus** [comment]
I can log in

**Comment by schadis** [comment]
i have the same error on a fresch account but for me this is happening since 2.0.2 @ startup
2.0.1 is working
