### ISSUE TITLE
(ERROR) System.NullReferenceException: Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by wallerstein2000** [PocketMobsters/MobBotTemp#38]
Please see below.

Happens after initial login. Get the string of error text. Then loads the 10 best Pokemon list. Get the error text again. Then the bot seems to run okay. Still catches pokemon, spins pokestops, etc. I am not sure if I am missing out some functionality indicated by the errors below.

[13:51:31] (ERROR) System.NullReferenceException: Object reference not set to an instance of an object.
   at PoGo.PokeMobBot.Logic.Tasks.CatchPokemonTask.<Execute>d__1.MoveNext() in C:\Users\Junior\Source\Repos\MobBotTemp\PoGo.PokeMobBot.Logic\Tasks\CatchPokemonTask.cs:line 131
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PoGo.PokeMobBot.Logic.Tasks.CatchLurePokemonsTask.<Execute>d__0.MoveNext() in C:\Users\Junior\Source\Repos\MobBotTemp\PoGo.PokeMobBot.Logic\Tasks\CatchLurePokemonsTask.cs:line 51
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PoGo.PokeMobBot.Logic.Tasks.FarmPokestopsGpxTask.<Execute>d__1.MoveNext() in C:\Users\Junior\Source\Repos\MobBotTemp\PoGo.PokeMobBot.Logic\Tasks\FarmPokestopsGPXTask.cs:line 85
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PoGo.PokeMobBot.Logic.State.FarmState.<Execute>d__0.MoveNext() in C:\Users\Junior\Source\Repos\MobBotTemp\PoGo.PokeMobBot.Logic\State\FarmState.cs:line 49
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PoGo.PokeMobBot.Logic.State.StateMachine.<Start>d__3.MoveNext() in C:\Users\Junior\Source\Repos\MobBotTemp\PoGo.PokeMobBot.Logic\State\StateMachine.cs:line 37

**Comment by XeonPowder** [comment]
im on it.
