### ISSUE TITLE
Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by jojoel** [PocketMobsters/MobBotTemp#50]
[07:07:54] Requesting routing info to xxxx
[07:08:26] Got response from xxxx
[07:08:26] System.NullReferenceException: Object reference not set to an instance of an object.
   at PoGo.PokeMobBot.Logic.HumanNavigation.<Move>d__2.MoveNext() in C:\Users\Junior\Source\Repos\MobBotTemp\PoGo.PokeMobBot.Logic\Navigation2.cs:line 73
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PoGo.PokeMobBot.Logic.Tasks.FarmPokestopsTask.<NoTeleport>d__3.MoveNext() in C:\Users\Junior\Source\Repos\MobBotTemp\PoGo.PokeMobBot.Logic\Tasks\FarmPokestopsTask.cs:line 354
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PoGo.PokeMobBot.Logic.Tasks.FarmPokestopsTask.<Execute>d__1.MoveNext() in C:\Users\Junior\Source\Repos\MobBotTemp\PoGo.PokeMobBot.Logic\Tasks\FarmPokestopsTask.cs:line 34
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at PoGo.PokeMobBot.Logic.State.FarmState.<Execute>d__0.MoveNext() in C:\Users\Junior\Source\Repos\MobBotTemp\PoGo.PokeMobBot.Logic\State\FarmState.cs:line 53
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PoGo.PokeMobBot.Logic.State.StateMachine.<Start>d__3.MoveNext() in C:\Users\Junior\Source\Repos\MobBotTemp\PoGo.PokeMobBot.Logic\State\StateMachine.cs:line 37
[07:08:26] Logging in using account Ptc
[07:08:29] Playing as

**Comment by XeonPowder** [comment]
perm banned.

**Comment by jojoel** [comment]
No it work. Now i can bot but some time it show error and relogin.

**Comment by XeonPowder** [comment]
hmm can you post your whole log on http://hastebin.com/ you can remove sensitive info if you want :)

**Comment by jojoel** [comment]
FYI.
http://hastebin.com/gequpayini.tex

**Comment by XeonPowder** [comment]
Its because of the routing server the not is using. We are trying to get our own server :) I'll see what I can do for this error specifically to let the users know why they are getting this error. So not to freak the users out. :)

**Comment by ziggrrauglurr** [comment]
Same error:

> [22:44:15] Arriving to Pokestop: Escultura A La Simplicidad in (2m)
> [22:44:15] Requesting routing info to www.yournavigation.org
> [22:44:36] Routing error: Unable to connect to the remote server
> [22:44:37] Name: Escultura A La Simplicidad XP: 50, Gems: 0, Items: 1 x ItemRevive, 2 x ItemPokeBall
> [22:44:40] System.NullReferenceException: Object reference not set to an instance of an object.
> at PoGo.PokeMobBot.Logic.Tasks.CatchPokemonTask.<Execute>d__1.MoveNext() in C:\Users\Junior\Source\Repos\MobBotTemp\PoGo.PokeMobBot.Logic\Tasks\CatchPokemonTask.cs:line 131
> --- End of stack trace from previous location where exception was thrown ---
> at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
> at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
> at PoGo.PokeMobBot.Logic.Tasks.CatchLurePokemonsTask.<Execute>d__0.MoveNext() in C:\Users\Junior\Source\Repos\MobBotTemp\PoGo.PokeMobBot.Logic\Tasks\CatchLurePokemonsTask.cs:line 51
> --- End of stack trace from previous location where exception was thrown ---
> at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
> at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
> at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
> at PoGo.PokeMobBot.Logic.Tasks.FarmPokestopsTask.<NoTeleport>d__3.MoveNext() in C:\Users\Junior\Source\Repos\MobBotTemp\PoGo.PokeMobBot.Logic\Tasks\FarmPokestopsTask.cs:line 455
> --- End of stack trace from previous location where exception was thrown ---
> at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
> at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
> at PoGo.PokeMobBot.Logic.Tasks.FarmPokestopsTask.<Execute>d__1.MoveNext() in C:\Users\Junior\Source\Repos\MobBotTemp\PoGo.PokeMobBot.Logic\Tasks\FarmPokestopsTask.cs:line 34
> --- End of stack trace from previous location where exception was thrown ---
> at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
> at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
> at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
> at PoGo.PokeMobBot.Logic.State.FarmState.<Execute>d__0.MoveNext() in C:\Users\Junior\Source\Repos\MobBotTemp\PoGo.PokeMobBot.Logic\State\FarmState.cs:line 53
> --- End of stack trace from previous location where exception was thrown ---
> at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
> at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
> at PoGo.PokeMobBot.Logic.State.StateMachine.<Start>d__3.MoveNext() in C:\Users\Junior\Source\Repos\MobBotTemp\PoGo.PokeMobBot.Logic\State\StateMachine.cs:line 37

So we wait for an alternative pathing server?
Can it be used with "old" human walking? What would be the option? (UseHumanPathing is true in my config). Thank you.

**Comment by XeonPowder** [comment]
hmm seems to be two different errors actually. For the first one I was wrong. and what i said for the first one applies to @ziggrrauglurr

**Comment by XeonPowder** [comment]
@ziggrrauglurr are you able to catch pokemon?

**Comment by ziggrrauglurr** [comment]
Account was catching pokemon normally in cellphone just 2 hours ago. The bot crashed as soon as tried pathing and catching, Log at http://pastebin.com/MZa9DKq1

**Comment by XeonPowder** [comment]
well i think i fixed @ziggrrauglurr's error but not @jojoel's (yet)

**Comment by XeonPowder** [comment]
its because some idiot wrote some code. also @ziggrrauglurr this issue was posted here: https://github.com/PocketMobsters/MobBotTemp/issues/38

**Comment by ziggrrauglurr** [comment]
Sorry, didn't see that one. This one looked similar, will test asap. 
(When release is available)
