### ISSUE TITLE
 (ERROR) PokemonGo.RocketAPI.Exceptions.LoginFailedException: Exception of type 'PokemonGo.RocketAPI.Exceptions.LoginFailedException' was thrown

### ISSUE THREAD

**Issue by Dragonzfire** [PocketMobsters/MobBotTemp#52]
Error recieved in 201 and 200. 

[21:56:53] (ERROR) PokemonGo.RocketAPI.Exceptions.LoginFailedException: Exception of type 'PokemonGo.RocketAPI.Exceptions.LoginFailedException' was thrown.
   at PokemonGo.RocketAPI.Login.PtcLogin.ExtracktTicketFromResponse(HttpResponseMessage loginResp) in C:\Users\Junior\Source\Repos\MobBotTemp\Pokemon-Go-Rocket-API\PokemonGo.RocketAPI\Login\PtcLogin.cs:line 49
   at PokemonGo.RocketAPI.Login.PtcLogin.<GetLoginTicket>d__8.MoveNext() in C:\Users\Junior\Source\Repos\MobBotTemp\Pokemon-Go-Rocket-API\PokemonGo.RocketAPI\Login\PtcLogin.cs:line 86
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Login.PtcLogin.<GetAccessToken>d__4.MoveNext() in C:\Users\Junior\Source\Repos\MobBotTemp\Pokemon-Go-Rocket-API\PokemonGo.RocketAPI\Login\PtcLogin.cs:line 38
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Rpc.Login.<DoLogin>d__3.MoveNext() in C:\Users\Junior\Source\Repos\MobBotTemp\Pokemon-Go-Rocket-API\PokemonGo.RocketAPI\Rpc\Login.cs:line 58
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PoGo.PokeMobBot.Logic.State.LoginState.<Execute>d__0.MoveNext() in C:\Users\Junior\Source\Repos\MobBotTemp\PoGo.PokeMobBot.Logic\State\LoginState.cs:line 31
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PoGo.PokeMobBot.Logic.State.StateMachine.<Start>d__3.MoveNext() in C:\Users\Junior\Source\Repos\MobBotTemp

**Comment by DaveG9856** [comment]
login failed........your banned

**Comment by XeonPowder** [comment]
well since it gives an error i can give a better reply such as (your banned, n00b)

**Comment by Dragonzfire** [comment]
Ok riddle me this.

Login works fine using NOX on SAME IP, or VPN IPs, can play etc no issues.
bot fails with 200, 201. Works fine with PokeMobBot_2016.08.11c.
Ran bot for 3 hours on 11c last night shut down for the night. Tried version 201 this morning and now that works.

So all things being even, something was not being caught in the code variations, but is now fine. Either data sent from Niantic, or magically the code on my machine bypassed he auto update set to false, and updated a library....

I only provided this information since last night in the dev channel there were mentions of bad commits in the master that needed fixed.

**Comment by XeonPowder** [comment]
no its just a thrown exception that isn't being caught

**Comment by Dragonzfire** [comment]
not banned at all, wasn't last night. I just wanted to share the information since I didn't know if they were shooting new data out and using it to screw with the detection. I was concerned since only the bot wasn't running on 200 when it did the night before without issue.

Again just trying to provide insight. It is all working fine now, but I don't know what changed...

**Comment by XeonPowder** [comment]
its good u posted it. it happens when you couldn't login to Pokemon Trainer Club

**Comment by XeonPowder** [comment]
there was some code missing to handle the error

**Comment by Dragonzfire** [comment]
Glad to help. closing the issue now that you guys are aware.

**Comment by XeonPowder** [comment]
https://github.com/PocketMobsters/MobBotTemp/commit/8bed58c7707732c237414894a2dbdcee865da1bb
